name: example
description: "Routing example"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: ">=3.16.0"

dependencies:
  # Flutter SDK
  flutter:
    sdk: flutter
  # Localization
  flutter_localizations:
    sdk: flutter

  # Routing
  octopus:
    path: ../

  # Utility
  l: ^4.1.0-pre.1
  meta: any

  # Storage
  shared_preferences: ^2.2.2

  # UI and Widgets
  cupertino_icons: ^1.0.2

dev_dependencies:
  # Unit & Widget tests for Flutter
  flutter_test:
    sdk: flutter
  # Integration tests for Flutter
  integration_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  shaders:
    - assets/shaders/shimmer.frag